version: '2.20'

services:
  db:
    image: postgres:14
    container_name: library_database
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/data/postgres
  
  app:
    build: .
    container_name: goapp
    ports:
      - "8080:8080"
    env_file:
      - .env

    depends_on:
      - db

volumes:
  db_data: